kind: pipeline
# 使用Docker执行器运行流水线
type: docker
name: default

trigger:
  branch:
    - main

# 挂载Docker套接字
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

steps:
  # 编译阶段
  - name: build
    image: node:latest
    commands:
      - npm i -g yarn
      - yarn install
      - yarn build

  # 部署阶段
  - name: deploy
    image: docker:cli
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      # 复制构建产物到nginx容器
      - docker cp /drone/src/dist my-nginx:/usr/share/nginx/html/
      - docker exec my-nginx nginx -s reload